### ISSUE TITLE
YAML scripts have timing dependencies that may be non-deterministic

### ISSUE THREAD

**Issue by tcarmelveilleux** [project-chip/connectedhomeip#10998]
#### Problem
Race conditions in CI were found (see https://github.com/project-chip/connectedhomeip/pull/10990)  where some test snippets did cluster updates that would expect time-base updates to values, followed by a read after that time to see if it worked.

Canonical example:

```
    - label: "sends a Move to level command"
      command: "MoveToLevel"
      arguments:
          values:
              - name: "level"
                value: 128
              - name: "transitionTime"
                value: 1
              - name: "optionMask"
                value: 1
              - name: "optionOverride"
                value: 1

    - label: "Wait 100ms"
      cluster: "DelayCommands"
      command: "WaitForMs"
      arguments:
          values:
              - name: "ms"
                value: 100

    - label: "reads current Level attribute from DUT"
      command: "readAttribute"
      attribute: "current Level"
      response:
          value: 128
```

In the above:

1. The first command has a `transitionTime` of 1, which, for the MoveToLevel command, is in units of 0.1s (100ms)
2. The second command is a delay, expecting that after 100ms, the command transition has occured fully
3. The third command attempts to see that the new value is updated

A symptom seen in CI is that sometimes the delay of 100ms is just not long enough for the actual real delay to have taken place in terms of the transition needed.

Upon further inspection of YAML files, it was found that there are many instances of time-based behavior, that fall in a few categories:

- Exact delay expected (leaving no margin for timer slop on targets)
- Very short delays (i.e. 1ms, or faster than what can be accounted for even on some RTOS platforms)
- Very long delays, with a lot of slop, proportional to the overall value

**In all cases, the YAML files did not explain with any comments or description the rationale for the exact value used, in a way that would help easily account for the validity or realism of the value used.**

 #### Proposed Solution

1. Audit any time-based delays in the test scripts (some targets have >=10ms minimum delay granularity, so a delay of 1ms won't scale to using that YAML against real devices)

2. Add comments above any time-based delays that explains exactly why that delay is there, including things like saying "Waiting 100ms + 20% before querying value since transitionTime is 1 (== 100ms) and therefore we cannot get updated value to have stabilized unless we wait longer"
