### ISSUE TITLE
Add command and verification capability to simulated device.

### ISSUE THREAD

**Issue by krypton36** [project-chip/connectedhomeip#11154]
#### Problem
There currently is not implementation of commands being execute from the Simulated device. In order to achieve the following tests, we need to be able to invoke commands from the simulated device to the controller. 

[Spec Example](https://github.com/CHIP-Specifications/connectedhomeip-spec/blob/c5ef32d756a6596df31371504eeab44dcca0d825/src/service_device_management/CommissioningFlows.adoc) Item 6. Requires response commands to be invoked. 

The following tests require validation from simulated device and commands need to be invoked to validate all paths of the Interaction Data Model. 
[3.1.1. [TC-IDM-1.1] Invoke Request Action from DUT to TH. [DUT - Controller/Commissioner]](https://github.com/CHIP-Specifications/chip-test-plans/blob/a5a498779fefe2d4cfa1141dc332120b91b561c6/src/interactiondatamodel.adoc#tc-idm-1-1-invoke-request-action-to-dut)
[3.2.1. [TC-IDM-2.1] Read Request Action from DUT to TH. [DUT - Controller/Commissioner]](https://github.com/CHIP-Specifications/chip-test-plans/blob/a5a498779fefe2d4cfa1141dc332120b91b561c6/src/interactiondatamodel.adoc#tc-idm-1-1-invoke-request-action-to-dut)
3.2.2. [TC-IDM-2.2] Report Data Action from DUT to TH. [DUT - Controller/Commissioner]
[3.3.1. [TC-IDM-3.1] Write Request Action from DUT to TH. [DUT - Controller/Commissioner]](https://github.com/CHIP-Specifications/chip-test-plans/blob/a5a498779fefe2d4cfa1141dc332120b91b561c6/src/interactiondatamodel.adoc#tc-idm-3-1-writerequestmessage-from-dut-test-cases)

Example Yaml :
Hopefully the syntax can be something like this :

```
name: 10.3.1. [TC-DM-3.1] Network Commissioning Attributes

config:
    cluster: "Network Commissioning"
    endpoint: 0

tests:
    - label: "Scan Network Response"
      command: "ScanNetworksResponse"
      wait: "ScanNetworks" # Waits for the command ScanNetworks and then executes the response
      response:
          constraints:
              type: list
      arguments:
          values:
              - name: "networkResponse"
                # The value is what is returned with the response command.
                value: {ErrorCode: 0, DebugText: “Hello World”, WiFiScanResults: [ {Security: 0x08, SSID: "Wifi-A", BSSID: "FF:FF:FF:FF:FF:FF", Channel: 11, FrequencyBand:6000,  RSSI: 65} ]}
```

[Test Case Link](https://github.com/CHIP-Specifications/chip-test-plans/blob/a5a498779fefe2d4cfa1141dc332120b91b561c6/src/devicediscovery.adoc#333-tc-dd-33-user-directed-commissioning---commissionee)
