### ISSUE TITLE
[Feature] Add UserPrompt command to YAML tests. 

### ISSUE THREAD

**Issue by trombadore** [project-chip/connectedhomeip#11853]
#### Problem
Scripters need a way to add user prompts to their YAML tests.

Currently there is only a log entry available in YAML like:
```
tests:
    - label: "Log a simple message"
      cluster: "LogCommands"
      command: "Log"
      arguments:
          values:
              - name: "message"
                value: "This is a simple message"
```

 #### Proposed Solution
Similarly to the `command: Log`, please add a `command: UserPrompt` or something to that equivalent so scripters can distinguish between lines they are trying to log and prompts they are trying to display to the user.

Please follow something like: 

```
tests:
    - label: "Display a user prompt."
      cluster: "LogCommands"
      command: "Prompt"
      arguments:
          values:
              - name: "message"
                value: "Please issue a ____ cluster from the DUT controller."
```

BUT append a prefix to the value like `"USER_PROMPT:"` so that log lines which are intended to be user prompts are clearly defined. 

So the logged output from that above example should look like: 

`USER_PROMPT: Please issue a ____ cluster from the DUT controller`
