### ISSUE TITLE
YAML: Cannot use SaveAs to compare 2 nullable of the same type

### ISSUE THREAD

**Issue by jmeg-sfy** [project-chip/connectedhomeip#14502]
#### Problem
../../zzz_generated/chip-tool/zap-generated/test/Commands.h:46603:35: error: assigning to 'chip::Percent100ths' (aka 'unsigned short') from incompatible type 'const chip::app::DataModel::Nullablechip::Percent100ths' (aka 'const Nullable')

---- example of what i did in YAML
```
    ### Read Current Position -> Store this value for step 4c
    - label:
          "4a: If (PA & TL) TH reads CurrentPositionTiltPercent100ths attribute
          from DUT"
      disabled: true
      command: "readAttribute"
      attribute: "CurrentPositionTiltPercent100ths"
      PICS: WNCV_TL && WNCV_PA_TL
      response:
          saveAs: attrCurrentPositionTilt
          constraints:
              minValue: 0
              maxValue: 10000

    ### Read Target Position -> Compare this value w/ Current
    ### Shall be tested as equals CurrentPositionTiltPercent100ths
    - label:
          "4b: If (PA & TL) TH reads TargetPositionTiltPercent100ths attribute
           4c: it Must be equal with CurrentPositionTiltPercent100ths from DUT"
      disabled: true
      command: "readAttribute"
      attribute: "TargetPositionTiltPercent100ths"
      PICS: WNCV_TL && WNCV_PA_TL
      response:
          value: attrCurrentPositionTilt
```
