### ISSUE TITLE
Need YAML support for test cases that run longer than 90 seconds

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#14748]
Summary:
               As per test plan of TC-OO-2.3 needs wait time more than 90 sec we are facing timeout error when we execute, need YAML framework support for test cases that run longer than 90 seconds

Execution screenshot:
![image](https://user-images.githubusercontent.com/84442963/152363442-07e0d8df-b80f-48ce-aa11-acc2c72aac9a.png)

**Comment by vivien-apple** [comment]
You can normally add a `timeout` parameter in the config section.

For example:
```
config:
   cluster: "Test Cluster"
   endpoint: 1
   timeout: 120 # or any number. It also generates a command line optional argument in case you need to customise that on the fly
```
