### ISSUE TITLE
[TC-I-2.2] Need YAML support for DUT response commands with arguments

### ISSUE THREAD

**Issue by manjunathambiger23** [project-chip/connectedhomeip#16113]
Summary:
               Need YAML support for the commands which gets response as commands from DUT with arguments below screenshot is the example from TC-I-2.2.
Testplan screenshot:
![image](https://user-images.githubusercontent.com/84442963/157870480-d2064566-6638-4d19-a7fa-40aa3ee795a2.png)

**Comment by bzbarsky-apple** [comment]
chip-tool supports this already:
```
      command: "IdentifyQuery"
      response:
          values:
              - name: "timeout"
                constraints:
                    minValue: 0
                    maxValue: 0x32
```
