### ISSUE TITLE
Support auto generation of optional arguments for yaml tests

### ISSUE THREAD

**Issue by carol-apple** [project-chip/connectedhomeip#17585]
#### Problem
For tests ran in the test suites, cluster command arguments are passed in via the yaml file. There is a way to specify that an argument is optional by adding `isOptional : true`. Using the `Start` command of SystemCommands cluster as an example:

```
const Start = {
  name : 'Start',
  arguments : [
    { 'name' : 'discriminator', type : 'INT16U', isOptional : true }, { 'name' : 'port', type : 'INT16U', isOptional : true }, { 'name' : 'kvs', type : 'CHAR_STRING', isOptional : true }
  ],
  response : { arguments : [] }
};
```

However, this translates to the generated Commands.h to call a particular cluster command function by not supplying the argument, rather than making it truly optional. For instance, if no arguments are supplied in the yaml file:
```
    - label: "Start the accessory with no command line options"
      command: "Start"
```

 The generated test code looks like:
```
CHIP_ERROR TestStartTheAccessoryWithNoCommandLineOptions_2()
    {
        SetIdentity(kIdentityAlpha);
        return Start();
    }
```

This works because SystemCommands.h declares the function like so:
```
CHIP_ERROR Start(uint16_t discriminator = 0xFFFF, uint16_t port = CHIP_PORT, const char * kvs = nullptr);
```

This is insufficient as the yaml file cannot just supply port or kvs. For example, this is not allowed:
```
    - label: "Start the accessory with only discriminator command line option"
      command: "Start"
      arguments:
          values:
              - name: "kvs"
                value: "/tmp/chip_kvs_test"
```

It must supply all "optional" arguments that come before it.

 #### Proposed Solution
Make the generated test code in Commands.h to support signatures like:
```
CHIP_ERROR Start(Optional<uint16_t> discriminator, Optional<uint16_t> port, Optional<chip::CharSpan> kvs);
```
