### ISSUE TITLE
chip-tool : Currently in the YAML scripts the PICS checks in each step are case-sensitive , can this be made case-insensitive please?

### ISSUE THREAD

**Issue by raju-apple** [project-chip/connectedhomeip#21425]
This issue was a major pain-point in SVE1 from a lot of participants

I'll explain with an example here : 
Currently in YAML scripts , if a step is something like this : 

```
    - label: "DUT executes a blink effect"
      cluster: "LogCommands"
      command: "UserPrompt"
      PICS: PICS_USER_PROMPT && I.S.C40.Rsp
      arguments:
          values:
              - name: "message"
                value: "Please enter 'y' for success"
              - name: "expectedValue"
                value: "y"
```

The PICS value I.S.C40.Rsp is case sensitive here , if the PICS tool or the test plan or spec changes it due to any reason or a manual error to either I.S.c40.Rsp or I.S.C40.RSP , the test case wouldn't execute as desired. We are trying to get all the scripts in sync here but would want the chip-tool to make any PICS values to be case - insensitive so that we don't run into these issues.
