### ISSUE TITLE
[SVE2] Octet strings escaped C style in Yaml cause test failure

### ISSUE THREAD

**Issue by bluebin14** [project-chip/connectedhomeip#21961]
#### Problem
Several Yaml's e.g. Test_TC_CADMIN_1_3.yaml declare octet strings escaped C style. This causes tast failure in all cases because raw binary data containing random control characters etc. is being passed on to chip-tool. Example:

```
    PakeVerifier:
        type: octet_string
        defaultValue:
          "\xb9\x61\x70\xaa\xe8\x03\x34\x68\x84\x72\x4f\xe9\xa3\xb2\x87\xc3\x03\x30\xc2\xa6\x60\x37\x5d\x17\xbb\x20\x5a\x8c\xf1\xae\xcb\x35\x04\x57\xf8\xab\x79\xee\x25\x3a\xb6\xa8\xe4\x6b\xb0\x9e\x54\x3a\xe4\x22\x73\x6d\xe5\x01\xe3\xdb\x37\xd4\x41\xfe\x34\x49\x20\xd0\x95\x48\xe4\xc1\x82\x40\x63\x0c\x4f\xf4\x91\x3c\x53\x51\x38\x39\xb7\xc0\x7f\xcc\x06\x27\xa1\xb8\x57\x3a\x14\x9f\xcd\x1f\xa4\x66\xcf"
```
The error in this case is:
`- Test Step Error: Error occurred during execution of test case TC_CADMIN_1_3. No closing quotation`

![THFail](https://user-images.githubusercontent.com/80577827/185085157-2180f24f-6852-40dd-a85f-f79d9f1a6310.png)

 #### Proposed Solution
Use "hex:b96170aa..." syntax for expressing octet strings containing binary data in yaml.
