### ISSUE TITLE
[Yaml] The CADMIN yaml test factory reset prompt

### ISSUE THREAD

**Issue by doublemis1** [project-chip/connectedhomeip#22035]
#### Problem

The CADMIN yaml scripts (e.g. https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CADMIN_1_3.yaml) inform us to proceed the factory reset, while the next step our DUT need to be already in the Matter Network
```
 - label: "TH_CR1 starts a commissioning process with DUT_CE"
      cluster: "DelayCommands"
      command: "WaitForCommissionee"
      PICS: CADMIN.S
      arguments:
          values:
              - name: "nodeId"
                value: nodeId
```
The Factory reset means that the device is back to the original state (not commissioned).
The same issue can be also observed in the test Harness tests while we want to factory reset the device and then the test script expects that the device is in the matter network.

 #### Proposed Solution

Add possibilities to provide a network data (e.g. thread dataset), qr-code/manual pairing code for the first commissioning.
Add a step to perform commissioning right after factory reset (if necessary)
