### ISSUE TITLE
[Feature] Add a timeout parameter to the subscribe attribute command in YAML

### ISSUE THREAD

**Issue by ericzijian1994** [project-chip/connectedhomeip#27804]
### Feature description

I was tried to add a `timeout` to the subscribeAttribute command in tests yaml, but it doesn't work.
What we tried to achieve is
<html>
<body>

SMCO.S.A0001(SmokeState) | After about 30 seconds, TH reads COState attribute from DUT | Verify that SmokeState attribute value
-- | -- | --

</body>
</html>

```yaml
- label: "TH subscribes to SmokeState attribute from DUT"
  PICS: SMCO.S.A0001
  endpoint: 1
  command: "subscribeAttribute"
  attribute: "SmokeState"
  minInterval: 3
  maxInterval: 60
  timeout: 300 # Not working
  response:
      value: 0
      constraints:
          type: enum8
```

And there is also no timeout parameter in the function.

```c++
CHIP_ERROR SubscribeEvent(const char * identity, chip::EndpointId endpointId, chip::ClusterId clusterId, chip::EventId eventId,
                          uint16_t minInterval, uint16_t maxInterval, bool fabricFiltered,
                          const chip::Optional<chip::EventNumber> & eventNumber, const chip::Optional<bool> & keepSubscriptions,
                          const chip::Optional<bool> & autoResubscribe);
```

It seems that a timeout parameter needs to be added to set the subscription time?

### Platform

all
