### ISSUE TITLE
[BUG] chip-tool compilation fails because of response variable

### ISSUE THREAD

**Issue by ericzijian1994** [project-chip/connectedhomeip#28096]
### Reproduction steps

In YAML, I used the saveAs variable in the response to the readEvent as follows:
```yaml
    - label:
          "TH waits for a report of InterconnectSmokeAlarm attribute from DUT"
      command: "waitForReport"
      attribute: "InterconnectSmokeAlarm"
      response:
          saveAs: tempAlarm

    - label: "TH reads InterconnectSmokeAlarm event from DUT"
      command: "readEvent"
      event: "InterconnectSmokeAlarm"
      response:
          value: { AlarmSeverityLevel: tempAlarm }
```

Then I compile chip-tool:
`./scripts/tools/zap_regen_all.py --type tests`
`scripts/examples/gn_build_example.sh examples/chip-tool out/chip-tool`

Finally I get this error:
[ninja_log.txt](https://github.com/project-chip/connectedhomeip/files/12102662/ninja_log.txt)

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

78c62b0e43b223a72e0aba40ef5090c308575182

### Platform

other

**Comment by bzbarsky-apple** [comment]
Simpler testcase:
```
    - label: "Read"
      cluster: "Smoke CO Alarm"
      command: "readAttribute"
      attribute: "InterconnectSmokeAlarm"
      response:
          saveAs: tempAlarm

    - label: "Verify"
      cluster: "Smoke CO Alarm"
      command: "readAttribute"
      attribute: "InterconnectSmokeAlarm"
      response:
          value: tempAlarm
```
