### ISSUE TITLE
Fix Step 3a of TC_xxxCONC_1_1

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#28838]
### Description

As part of #28361, Step 3a of `TC_xxxCONC_1_1` was edited to check for 0 if no feature flags were set, e.g:

```
    - label:
          "Step 3a: Read the global attribute: FeatureMap and check for either
          bit 0 or 1 set"
      PICS:
          " !OZCONC.S.F00 && !OZCONC.S.F01 && !OZCONC.S.F02 && !OZCONC.S.F03 &&
          !OZCONC.S.F04 && !OZCONC.S.F05"
      command: "readAttribute"
      attribute: "FeatureMap"
      response:
          value: 0
          constraints:
              type: bitmap32
```

Technically, this is incorrect, as a scenario where no feature PICS are set is not a valid one. 

The test is trying to cover the fact that the `MEA` feature and the `LEV` feature have `O.a+` conformance. 

This is covered in the Test Plan via the statement: 

> At least one of bit 0 and bit 1 SHALL be 1.

So, this test step needs to be reverted to test for that.
