### ISSUE TITLE
[BUG] TC-SC-4.1 fails to execute FindCommissionable command

### ISSUE THREAD

**Issue by rquidute** [project-chip/connectedhomeip#29012]
### Reproduction steps

Step to reproduce:
1. Run TC-SC-4.1 in TH
2. Test fails at step `Step 7a: DNS-SD instance name must be 64-bit randomly selected ID expressed as a sixteen-char hex string with capital letters`  

### Bug prevalence

Always

### GitHub hash of the SDK that was being used

cb83d1ef7376da8e0685e23f5285333c8ce3c4d4

### Platform

python

### Anything else?

This is the request and response for the related test step:

- Request: 
`'json:{ "cluster": "discover", "command": "commissionables", "arguments" : "base64:eyAgfQ==" }'`

- Response: 
`'{  "results": [{ "error": "FAILURE" }],"logs": [{  "module": "TOO",  "category": "Info",  "message": "Q29tbWFuZDogZGlzY292ZXIgY29tbWlzc2lvbmFibGVzIA=="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBjYWNoZSBleGhhdXN0ZWQ="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBhbGwgZm9yIG5vdw=="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBjYWNoZSBleGhhdXN0ZWQ="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBhbGwgZm9yIG5vdw=="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBjYWNoZSBleGhhdXN0ZWQ="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBhbGwgZm9yIG5vdw=="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBjYWNoZSBleGhhdXN0ZWQ="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBhbGwgZm9yIG5vdw=="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBjYWNoZSBleGhhdXN0ZWQ="},{  "module": "DL",  "category": "Info",  "message": "QXZhaGkgYnJvd3NlOiBhbGwgZm9yIG5vdw=="}]}'`

- This is the step in YAML script:
```
    - label:
          "Step 7a: DNS-SD instance name must be 64-bit randomly selected ID
          expressed as a sixteen-char hex string with capital letters"
      cluster: "DiscoveryCommands"
      command: "FindCommissionable"
      response:
          values:
              - name: "instanceName"
                constraints:
                    minLength: 16
                    maxLength: 16
                    isUpperCase: true
                    isHexString: true
```
