### ISSUE TITLE
[SVE] [TC-ACL-2.10] Step 10 fails after DUT is rebooted

### ISSUE THREAD

**Issue by jrhees-cae** [project-chip/connectedhomeip#29164]
### Reproduction steps

TC-ACL-2.10 fails step 10 after DUT is rebooted in step 9. It appears that this is because TH1 is still attempting to use the the previous CASE session and therefore fails.

If I remove the PICS_SDK_CI_ONLY from the following step in the YAML (the step immediately after the reboot, but before step 10), I can get the test to run successfully:
```
    - label: "TH1 Connects to the device again"
      PICS: PICS_SDK_CI_ONLY
      cluster: "DelayCommands"
      command: "WaitForCommissionee"
      arguments:
          values:
              - name: "nodeId"
                value: nodeId
```

I am testing with a Thread DUT.

### Bug prevalence

Consistent

### GitHub hash of the SDK that was being used

5ccb774e7e5fe7ead3ff85bec1cda31a459c9c37

### Platform

raspi

### Type

Test Improvement

### Testing

YAML tested
