### ISSUE TITLE
[CERT-TEST-FAILURE] TestDiscovery expects the same instancename in multiple commissioning windows

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#29457]
### Feature Area

Other

### Test Case

TestDiscovery

### Reproduction steps

I know that this is an chip internal testing too and no certification test but still wonder why the test is as it is.

The specs tell:
> A new instance name SHALL be selected when the Node boots. A new instance name SHALL be selected whenever the Node enters Commissioning mode.

This test starts a device and saves the instance name ... then at the end it opens a new commissioning window and exects that the instance id is the same.

Do I get this test logic right?
Because if yes and if the chip tool based apps fullfill them then they are implemented against specs ... or do I miss anything here? Is the spec wrong or the implementation/test @bzbarsky-apple  ?

Thank you for clarification.

### Bug prevalence

always

### GitHub hash of the SDK that was being used

current master

### Platform

core

**Comment by bzbarsky-apple** [comment]
> then at the end it opens a new commissioning window and exects that the instance id is the same.

Where do you see that, @Apollon77 ?  What I see in the YAML is:
```
    - label: "Check Instance Name"
      cluster: "DiscoveryCommands"
      command: "FindCommissionable"
      response:
          values:
              - name: "instanceName"
                constraints:
                    minLength: 16
                    maxLength: 16
                    isUpperCase: true
                    isHexString: true
                    notValue: deviceInstanceNameBeforeReboot
```
which is checking that the value of `instanceName` is _not the same_ as `deviceInstanceNameBeforeReboot`
