### ISSUE TITLE
TC-FAN-2.1: Deprecated Values should be removed from Step 2

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#31230]
Follow up from [this issue](https://github.com/CHIP-Specifications/chip-test-plans/issues/3490) in the Test Plan. 

```
    - label: "Step 2: TH reads from the DUT the the FanMode attribute"
      PICS: FAN.S.A0000
      command: "readAttribute"
      attribute: "FanMode"
      response:
          constraints:
              type: enum8
              minValue: 0
              maxValue: 6
```

The range 0-6 includes deprecated values so is the wrong expected outcome. 

Should be:

```
          constraints:
              type: enum8
              anyOf: [0, 1, 2, 3, 5]
```

On hold until Test Plan update is merged
