### ISSUE TITLE
TC-CONC-2.1: Adds Uncertainty Check

### ISSUE THREAD

**Issue by mhazley** [project-chip/connectedhomeip#31263]
Follow up from [this issue](https://github.com/CHIP-Specifications/chip-test-plans/issues/3540) in the Test Plan. 

The uncertainty value was never checked.

All 2.1 tests should include step:

e.g. for CO2
```
    - label: "Step 12: TH reads from the DUT the Uncertainty attribute."
      PICS: CDOCONC.S.A0007
      command: "readAttribute"
      attribute: "Uncertainty"
      response:
          constraints:
              type: single
              minValue: 0
```

On hold until Test Plan update is merged
