### ISSUE TITLE
[1.3] TC-TMP-2.1 uses invalid YAML and has PICS set incorrectly.

### ISSUE THREAD

**Issue by cecille** [project-chip/connectedhomeip#32835]
### Reproduction steps

```
Step 3:
    - label: "Step 3: TH reads the MaxMeasuredValue attribute from the DUT"
      PICS: TMP.S.A0002
      command: "readAttribute"
      attribute: "MaxMeasuredValue"
      response:
          saveAs: CurrentMaxMeasured
          constraints:
              type: int16s
              minValue: CurrentMinMeasured+1
              maxValue: 32767
   ```
Arithmetic expressions are not supported in yaml, which means "CurrentMinMeasured+1" is invalid. It also means that the CI is not running this step. Probably because the PICS is set incorrectly, even though this is a mandatory attribute.
          

### Bug prevalence

always

### GitHub hash of the SDK that was being used

e53dca89c1533b79a6ff8da8e3e9ee14e449770a

### Platform

other

### Platform Version(s)

yaml;

### Type

Test Improvement
