### ISSUE TITLE
[CERT-TEST-FAILURE] [SUPPORT] Issue encountered with setting the PIXIT.WNCV.FULLMOTION value in the TC-WNCV YAML tests.

### ISSUE THREAD

**Issue by MarijanaJo98** [project-chip/connectedhomeip#33067]
### Feature Area

Other

### Test Case

TC-WNCV-4.1, TC-WNCV-4.2

### Reproduction steps

When executing **Window Covering YAML tests** within the Matter test harness on the virtual machine (Version: 2.10-beta3+spring2024 Sha: e182d0f), I encountered an issue where I was unable to configure the value for **PIXITI.WNCW.FULLMOTION**. 

I have provided screenshots of the PICS file with supported configurations and the project setup. The intention was to set the value of **PIXITI.WNCW.FULLMOTION** to 14 seconds. However, even after configuring this value, when I initiate tests **TC_WNCV_4.1** and **TC_WNCV_4.2**, the default value in the test remains unchanged at 6000 ms. 

Could you guide how to overwrite this default value effectively?

I have seen in your _Test_TC_WNCV_4_1.yaml_ in config there is fullMotionDuration parameter with default value: 

```
name:
    Window Covering [TC-WNCV-4.1] GoToLiftPercentage command Long-Run
    Verification [DUT as Server]

PICS:
    - WNCV.S

config:
    nodeId: 0x12344321
    cluster: "Window Covering"
    endpoint: 1
    fullMotionDuration:
        type: int16u
        defaultValue: 6000
```

**PICS setup:**
<img width="895" alt="PICS" src="https://github.com/project-chip/connectedhomeip/assets/74305345/a03fe47b-6fa0-4b5b-9707-e3be5275f882">

**Project Configuration setup:**
<img width="587" alt="WindowCoveringConf" src="https://github.com/project-chip/connectedhomeip/assets/74305345/1b52b422-742a-4c03-8b2b-d151436918c8">

I attempted to set the value using both hexadecimal and milliseconds, but encountered the same result each time.
Thanks in advance.

### Bug prevalence

Consistently reproducible

### GitHub hash of the SDK that was being used

9f6d627e0262e1d023986291948bb4e845be803e

### Platform

other
