### ISSUE TITLE
[CERT-TEST-FAILURE] Test_TC_CC_5_3 Min/Max values checked in step 3d and 3c are the same which fails transitions

### ISSUE THREAD

**Issue by Apollon77** [project-chip/connectedhomeip#33326]
### Feature Area

Other

### Test Case

TC_CC_5_3

### Reproduction steps

The testcase Test_TC_CC_5_3 is testing some hiue and saturation transitions. Here in step 3c some values are checked after 10s of transitionioning. Then it waits another 5s and checks in 3d again ... but here the same values are used which indeed fails becaus ethe transition is 5s further in time.

https://github.com/project-chip/connectedhomeip/blob/master/src/app/tests/suites/certification/Test_TC_CC_5_3.yaml#L154-L170

When I use the same rate for min/max used between 3b->3c and half them I come to the followijg boundaries

```
    - label: "Step 3d: TH reads CurrentX attribute from DUT"
      command: "readAttribute"
      PICS: CC.S.F03 && CC.S.A0003 && CC.S.C08.Rsp
      attribute: "CurrentX"
      response: 
          constraints: 
              minValue: 5925
              maxValue: 10075
      
    - label: "Step 3d: TH reads CurrentY attribute from DUT"
      command: "readAttribute"
      PICS: CC.S.F03 && CC.S.A0004 && CC.S.C08.Rsp
      attribute: "CurrentY"
      response:
          constraints: 
              minValue: 10850
              maxValue: 14150
```

I came across this while implementing ColorControl for matter.js.
Here the values while checking 3b are:
* currentX: 13000
* currentY: 14000

And in 3d they are:
* currentX: 8000
* currentY: 12500

### Bug prevalence

always for me

### GitHub hash of the SDK that was being used

master

### Platform

core

### Anything else?

The other question would be why chip tool tests in CI did not have the same issue, unless they somehow transition differently (which would be very strange).
