### ISSUE TITLE
[BUG] [zephyr] Use connectedhomeip as a zephyr module

### ISSUE THREAD

**Issue by QuentinCaldeira-eaton** [project-chip/connectedhomeip#33471]
### Reproduction steps

Hello, I'm trying to use connectedhomeip as a zephyr OS module. To do so, connectedhomeip is pulled from zephyr's west.yaml like this:
```yaml
- name: connectedhomeip
      remote : connectedhomeip
      revision: 648d7bf3d2e52ded740c94989965cd8485c85832
      path: modules/lib/matter
      submodules:
        - name: nlio
          path: third_party/nlio/repo
        - name: nlassert
          path: third_party/nlassert/repo
        - name: nlunit-test
          path: third_party/nlunit-test/repo
        - name: pigweed
          path: third_party/pigweed/repo
        - name: jsoncpp
          path: third_party/jsoncpp/repo
```
Next, I moved the zephyr folder in `config/zephyr/chip-module` to the root, and changed the paths to Kconfig and CMakeList. 

My goal is to include the Kconfig `CONFIG_CHIP=y` in a standalone zephyr application, and see it compiled. My final goal is to compile a Matter zephyr application on an STM32 target. For now, I've added the Kconfig `CONFIG_CHIP` to the hello_world sample in `zephyr/samples/cpp`.

When I west build, I first get an error about chip_build_pw_rpc_lib = false, like this [one](https://github.com/project-chip/connectedhomeip/issues/27153). Then if I bypass this error, I get hundreds of other errors. 

I had understood that the zephyr platform could be used standalone. Is there another way to use connectedhomeip as a zephyr module?

### Bug prevalence

Whenever I do this

### GitHub hash of the SDK that was being used

648d7bf3d2e52ded740c94989965cd8485c85832

### Platform

other

### Anything else?

[log.txt](https://github.com/project-chip/connectedhomeip/files/15321848/log.txt)
