### ISSUE TITLE
[1.3] Failed to generate and build a Basic Video Player matter/chef example for efr32 platform

### ISSUE THREAD

**Issue by mlsg** [project-chip/connectedhomeip#33802]
### Reproduction steps

I fail to generate and compile the Basic Video player example using the chef script. 
I followed the instructions from the Chef example as follows: 

1.  Run chef.py the first time to create a config.yaml configuration file
2. Update your the SDK paths on config.yaml
3. Run $ chef.py -u to update zap and the toolchain
4. Run ./chef.py -zbf -t silabs-thread -d rootnode_basicvideoplayer_0ff86e943b

Config.yaml content is shown below:
```
ameba:
  AMEBA_SDK: null
  MATTER_SDK: null
  MODEL: D
  TTY: null
esp32:
  IDF_PATH: null
  TTY: null
nrfconnect:
  TTY: null
  ZEPHYR_BASE: null
  ZEPHYR_SDK_INSTALL_DIR: null
silabs-thread:
  CU: null
  GECKO_SDK: /home/mgrcic/SimplicityStudio/SDKs/gecko_sdk
  SILABS_BOARD: BRD2601B
  TTY: /dev/ttyACM0
telink:
  TTY: null
  ZEPHYR_BASE: null
  ZEPHYR_SDK_INSTALL_DIR: null
```

I get following error every time after executing commnd Run ./chef.py -zbf -t silabs-thread -d rootnode_basicvideoplayer_0ff86e943b: 

+ gn gen --check --script-executable=/home/mgrcic/workspace/matter/connectedhomeip/.environment/pigweed-venv/bin/python3 --fail-on-unused-args --export-compile-commands --root=./ --dotfile=/home/mgrcic/workspace/matter/connectedhomeip/examples/chef/openthread.gn '--args=silabs_board="BRD4161A" sample_name="rootnode_basicvideoplayer_0ff86e943b" enable_openthread_cli=true chip_build_libshell=true sl_matter_version_str="v1.2-HEAD-5bb5c9e23d-dirty" ' out/rootnode_basicvideoplayer_0ff86e943b/BRD4161A
ERROR Could not load dotfile.
The file "/home/mgrcic/workspace/matter/connectedhomeip/examples/chef/openthread.gn" couldn't be loaded.
Traceback (most recent call last):
  File "/home/mgrcic/workspace/matter/connectedhomeip/examples/chef/./chef.py", line 1011, in <module>
    sys.exit(main())
  File "/home/mgrcic/workspace/matter/connectedhomeip/examples/chef/./chef.py", line 753, in main
    shell.run_cmd(" ".join(efr32_cmd_args))
  File "/home/mgrcic/workspace/matter/connectedhomeip/examples/chef/stateful_shell.py", line 139, in run_cmd
    raise RuntimeError(
RuntimeError: Error. Nonzero return code.
Returncode: 1
Cmd: /home/mgrcic/workspace/matter/connectedhomeip/examples/chef/../..//scripts/examples/gn_silabs_example.sh ./ out/rootnode_basicvideoplayer_0ff86e943b BRD4161A 'sample_name="rootnode_basicvideoplayer_0ff86e943b"' enable_openthread_cli=true chip_build_libshell=true

I am asking you for instructions to do this to the end.
Best Rergards

### Bug prevalence

every time I run chef.py

### GitHub hash of the SDK that was being used

5bb5c9e23d532cea40476fc0bd1d3008522792ba

### Platform

efr32

### Type

Platform Issue
