### ISSUE TITLE
Improve overall code / test quality

### ISSUE THREAD

**Issue by erjiaqing** [project-chip/connectedhomeip#5680]
#### Problem
In recent 5 checks on master branch, the cirque tests
Break 1 times on OnOff test
Break 3 times on Echo test
Break 1 times on MobileDevice test (#5679)

After reviewing the logs
1. The OnOff cluster test breaks on:
```
2021-03-29 14:38:33,260 [CHIPOnOffTest] INFO device: CHIP-Tool(7225390b...) exec: chip-tool onoff on 1
2021-03-29 14:38:33,342 [CHIPOnOffTest] INFO command return code: 1
2021-03-29 14:38:33,342 [CHIPOnOffTest] INFO command output: 
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:ZCL: Using ZAP configuration...
CHIP:ZCL: deactivate report event
CHIP:DL: CHIP task running
CHIP:TOO: Init failure! No pairing for device: 112233
CHIP:CTL: Shutting down the commissioner
CHIP:CTL: Shutting down the controller
CHIP:DL: System Layer shutdown
CHIP:DL: Inet Layer shutdown
CHIP:DL: BLE layer shutdown
CHIP:TOO: Run command failure: CHIP Error 4072 (0x00000FE8): Not connected
```

2. Mobile device crashed on
```
Segmentation fault (core dumped)
*** Segmentation fault
Register dump:

 RAX: 2d8292e87f8d12bd   RBX: 000000000218a680   RCX: 0000000000000000
 RDX: 0000000000000000   RSI: 0000000000000000   RDI: 000000000218d568
 RBP: 00007f54377fd700   R8 : 00007f5447951f6d   R9 : 000000000000001e
 R10: 00007f5447a58070   R11: 0000000000000000   R12: 000000000218d618
 R13: 0000000000000000   R14: 0000000000000001   R15: 0000000000000000
 RSP: 00007f54377fd6f0

 RIP: 00007f54479b26e4   EFLAGS: 00010202

 CS: 0033   FS: 0000   GS: 0000

 Trap: 0000000d   Error: 00000000   OldMask: 00000000   CR2: 00000000

 FPUCW: 0000037f   FPUSW: 00000000   TAG: 00000000
 RIP: 00000000   RDP: 00000000

 ST(0) 0000 0000000000000000   ST(1) 0000 0000000000000000
 ST(2) 0000 0000000000000000   ST(3) 0000 0000000000000000
 ST(4) 0000 0000000000000000   ST(5) 0000 0000000000000000
 ST(6) 0000 0000000000000000   ST(7) 0000 0000000000000000
 mxcsr: 1fa0
 XMM0:  00000000000000000000000025252525 XMM1:  00000000000000000000000025252525
 XMM2:  00000000000000000000000025252525 XMM3:  00000000000000000000000025252525
 XMM4:  00000000000000000000000025252525 XMM5:  00000000000000000000000025252525
 XMM6:  00000000000000000000000025252525 XMM7:  00000000000000000000000025252525
 XMM8:  00000000000000000000000025252525 XMM9:  00000000000000000000000025252525
 XMM10: 00000000000000000000000025252525 XMM11: 00000000000000000000000025252525
 XMM12: 00000000000000000000000025252525 XMM13: 00000000000000000000000025252525
 XMM14: 00000000000000000000000025252525 XMM15: 00000000000000000000000025252525

Backtrace:
/usr/local/lib/python3.8/dist-packages/chip/_ChipDeviceCtrl.so(_ZN4chip17RendezvousSession11UpdateStateENS0_5StateEi+0x184)[0x7f54479b26e4]
```

3. EchoTest failed on
```
2021-03-29 20:42:26,096 [CHIPEchoTest] INFO device: CHIP-Echo-Requester(04ff2146...) exec: chip-echo-requester 172.18.0.3
2021-03-29 20:42:26,574 [CHIPEchoTest] INFO command return code: 134
2021-03-29 20:42:26,574 [CHIPEchoTest] INFO command output: 
Init CHIP Stack
CHIP:DL: writing settings to file (/tmp/chip_factory.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_factory.ini)
CHIP:DL: writing settings to file (/tmp/chip_config.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_config.ini)
CHIP:DL: writing settings to file (/tmp/chip_counters.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIP:DL: CHIP task running
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
Establish secure session succeeded

Send echo request message to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 0x000000000001b669to 0x0000000000bc5c01
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:EM: Rxd Ack; Removing MsgId:00000000 from Retrans Table
CHIP:EM: Removed CHIP MsgId:00000000 from RetransTable
CHIP:EM: Piggybacking Ack for MsgId:00000000 with msg

2021-03-29 20:42:26,574 [CHIPEchoTest] ERROR Echo failure: Init CHIP Stack
CHIP:DL: writing settings to file (/tmp/chip_factory.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_factory.ini)
CHIP:DL: writing settings to file (/tmp/chip_config.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_config.ini)
CHIP:DL: writing settings to file (/tmp/chip_counters.ini.tmp)
CHIP:DL: renamed tmp file to file (/tmp/chip_counters.ini)
CHIP:DL: CHIP task running
CHIP:IN: TransportMgr initialized
CHIP:IN: local node id is 0x000000000001b669
CHIP:IN: New pairing for device 0x0000000000bc5c01, key 0!!
Establish secure session succeeded

Send echo request message to Node: 12344321
CHIP:IN: Secure message was encrypted: Msg ID 0
CHIP:IN: Sending msg from 0x000000000001b669to 0x0000000000bc5c01
CHIP:IN: Sending secure msg on generic transport
CHIP:IN: Secure msg send status 0
CHIP:EM: Rxd Ack; Removing MsgId:00000000 from Retrans Table
CHIP:EM: Removed CHIP MsgId:00000000 from RetransTable
CHIP:EM: Piggybacking Ack for MsgId:00000000 with msg

Traceback (most recent call last):
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 62, in run_test
    self.test_routine()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-echo.py", line 64, in test_routine
    self.run_data_model_test()
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/test-echo.py", line 79, in run_data_model_test
    self.assertEqual(
  File "/home/runner/work/connectedhomeip/connectedhomeip/src/test_driver/linux-cirque/helper/CHIPTestBase.py", line 222, in assertEqual
    raise AssertionError
AssertionError
```

 #### Proposed Solution

These error are not caused by the tests, but the code, we should fix the code to resolve these issues.

Also, these failure does not happen every time, so please rerun it if it is failed
