### ISSUE TITLE
Virtualize System and Inet interfaces

### ISSUE THREAD

**Issue by andy31415** [project-chip/connectedhomeip#7715]
#### Problem
SystemLayer and InetLayer are passed around as pointer already in many places, however they still are not flexible:
  - DeviceLayer::SystemLayer and similar are used to access a global
  - The classes are fixed and implementation is `#ifdef` depending on build

We need to cleanup the `#ifdef` style of conditionals for readability and maintenance.

We want to be able to perform functional and endtoend tests in our code. We are able to do full simulation (e.g. docker/cirque) however for performance it seems better to be able to have 'mock interfaces' to simulate CHIP nodes within a single process and run tests faster rather than spinning up new applications or docker images.

 #### Proposed Solution
- Virtualize Inet and System layer
- Separate _Impl.cpp that are chosen by the build script instead of having `#ifdef` usage
- Pass the layers as needed instead of relying on DeviceLayer to access global state

**Comment by electrocucaracha** [comment]
One alternative for this it is using [Vagrant tool](https://www.vagrantup.com/), it allows to declare as many as NICs as needed in their `Vagrantfile`

```ruby
Vagrant.configure("2") do |config|
  config.vm.network :private_network, ip: "192.168.0.2", type: :static, libvirt__network_name: "mgmt", nic_type: "virtio"
  config.vm.network :private_network, ip: "10.0.0.2", type: :static, libvirt__network_name: "private", nic_type: "virtio"
end
```
And it's supported on the [macOS 10.15 virtual environment](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md#utilities) so it's possible to consume it in a GitHub Action.

```yaml
name: Check CI
# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  check-e2e:
    runs-on: macos-10.15
    env:
      VAGRANT_DISABLE_VBOXSYMLINKCREATE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-
      - name: Create Virtual Machine
        run: vagrant up
```
